### PR TITLE
Block bad installs and improve authoring messages

### LINKED ISSUE #1492: Templates with no short name should warn and not install
Add another install time check that verifies that `shortName` exists. If it doesn't notify the user and skip installing the template

### LINKED ISSUE #1498: "dotnet new" fails to install a new template with "node_modules" with "Error: Value cannot be null" message
_From @dance2die on April 4, 2018 1:36_

## Steps to reproduce
1. Create a new `dotnet new` SPA project, `react`.
```bash
dance2die@LELOUCH c:\misc\sources\github
> dotnet new react -n ThisFails
The template "ASP.NET Core with React.js" was created successfully.

Processing post-creation actions...
...
Manual instructions: Run "npm install"
```
2. Go to the newly created project.
```bash
dance2die@LELOUCH c:\misc\sources\github
> cd ThisFails
```
3. Install NPM packages.
```bash
dance2die@LELOUCH c:\misc\sources\github\ThisFails
> npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
...
added 546 packages in 136.886s
```
4. Add a new template folder, `.template.config` and a new configuration file, `template.json`.
5. Copy the following configuration to `template.json` file.
```javascript
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Sung Kim",
  "classifications": ["Web"],
  "name": "BadTemplate",
  "identity": "BadTemplate",
  "shortName": "badtemplate",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "sourceName": "BadTemplate",
  "preferNameDirectory": true
}
```
6. Go up one directory.
```bash
dance2die@LELOUCH c:\misc\sources\github\ThisFails
> cd ..
```
7. Install the template, `ThisFails`.
```bash
dance2die@LELOUCH c:\misc\sources\github
> dotnet new -i .\ThisFails
Error: Could not install ".\ThisFails".
Error: Value cannot be null.
Parameter name: key
...
Examples:
    dotnet new mvc --auth Individual
    dotnet new mstest
    dotnet new --help
```
## Expected  behavior
Go to the `ThisFails` folder and delete `node_modules` folder.
```bash
dance2die@LELOUCH c:\misc\sources\github
> cd ThisFails
dance2die@LELOUCH c:\misc\sources\github\ThisFails
> rmdir /S /Q node_modules
```
Go up one directory
```bash
dance2die@LELOUCH c:\misc\sources\github\ThisFails
> cd ..
```
Installing works without an error.
```bash
dance2die@LELOUCH c:\misc\sources\github
> dotnet new -i .\ThisFails
Templates                                         Short Name       Language          Tags
--------------------------------------------------------------------------------------------------------
...
BadTemplate                                       badtemplate      [C#]              Web
...
Examples:
    dotnet new mvc --auth Individual
    dotnet new console
    dotnet new --help
```

## Actual behavior
Fails with following error message.
```bash
dance2die@LELOUCH c:\misc\sources\github                                                                
> dotnet new -i .\ThisFails                                                                             
Error: Could not install ".\ThisFails".                                                                 
Error: Value cannot be null.                                                                            
Parameter name: key                                                                                     
Templates                                         Short Name       Language          Tags               
--------------------------------------------------------------------------------------------------------
Console Application                               console          [C#], F#, VB      Common/Console     
Class library                                     classlib         [C#], F#, VB      Common/Library     
Unit Test Project                                 mstest           [C#], F#, VB      Test/MSTest        
xUnit Test Project                                xunit            [C#], F#, VB      Test/xUnit         
BadTemplate                                       badtemplate      [C#]              Web                
ASP.NET Core Empty                                web              [C#], F#          Web/Empty          
ASP.NET Core Web App (Model-View-Controller)      mvc              [C#], F#          Web/MVC            
ASP.NET Core Web App                              razor            [C#]              Web/MVC/Razor Pages
ASP.NET Core with Angular                         angular          [C#]              Web/MVC/SPA        
ASP.NET Core with React.js                        react            [C#]              Web/MVC/SPA        
ASP.NET Core with React.js and Redux              reactredux       [C#]              Web/MVC/SPA        
ASP.NET Core Web API                              webapi           [C#], F#          Web/WebAPI         
global.json file                                  globaljson                         Config             
Nuget Config                                      nugetconfig                        Config             
Web Config                                        webconfig                          Config             
Solution File                                     sln                                Solution           
Razor Page                                        page                               Web/ASP.NET        
MVC ViewImports                                   viewimports                        Web/ASP.NET        
MVC ViewStart                                     viewstart                          Web/ASP.NET        
                                                                                                        
                                                                                                        
Examples:                                                                                               
    dotnet new mvc --auth Individual                                                                    
    dotnet new mstest                                                                                   
    dotnet new --help                                                                                   
```

## Environment data
```bash
dance2die@LELOUCH c:\misc\sources\github\ThisFails   
> dotnet --info                                      
.NET Command Line Tools (2.0.2)                      
                                                     
Product Information:                                 
 Version:            2.0.2                           
 Commit SHA-1 hash:  a04b4bf512                      
                                                     
Runtime Environment:                                 
 OS Name:     Windows                                
 OS Version:  10.0.16299                             
 OS Platform: Windows                                
 RID:         win10-x64                              
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\     
                                                     
Microsoft .NET Core Shared Framework Host            
                                                     
  Version  : 2.0.0                                   
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

_Copied from original issue: dotnet/cli#8989_

### PR DESCRIPTION
**Pull request by mlorbetske**
Fixes #1492

Fixes #1498 

Example output from the repro in #1498
```
D:\Projects\repro>dotnet new3 -i .\ThisFails --trace:authoring
Authoring: '/ClientApp/node_modules/caniuse-db/features-json/template.json' was not installed
Authoring:     Missing 'identity' in '/ClientApp/node_modules/caniuse-db/features-json/template.json'
Authoring:     Missing 'name' in '/ClientApp/node_modules/caniuse-db/features-json/template.json'
Authoring:     Missing 'sourceName' in '/ClientApp/node_modules/caniuse-db/features-json/template.json'
Authoring:     Missing 'shortName' in '/ClientApp/node_modules/caniuse-db/features-json/template.json'
Usage: new3 [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.


Templates                Short Name       Language          Tags
--------------------------------------------------------------------------
Console Application      console          [C#], F#, VB      Common/Console
Class library            classlib         [C#], F#, VB      Common/Library
Unit Test Project        mstest           [C#], F#, VB      Test/MSTest
xUnit Test Project       xunit            [C#], F#, VB      Test/xUnit
BadTemplate              badtemplate      [C#]              Web
global.json file         globaljson                         Config
NuGet Config             nugetconfig                        Config
Web Config               webconfig                          Config
Solution File            sln                                Solution

Examples:
    dotnet new3 mstest
    dotnet new3 classlib --framework netcoreapp2.0
    dotnet new3 --help

D:\Projects\repro>
```

### CODE REVIEW

**Comment by mlorbetske** [comment]
Posting the sequence of events that were intended for the PR and not #1492 /facepalm

**(Added WIP tag)**

**Message 1:**
This is causing tests to fail, either the new restrictions will need to be relaxed or the test assets will need to be fixed up. The former approach will likely be taken to avoid impacting existing templates.

**Message 2:**
Turns out the test to avoid regressing #651 came in handy 😄

I've updated the validations to add warnings for missing common properties that won't fail the install and corrected some messaging. An update will be coming soon.

**(Pushed new commit)**

**(Removed WIP tag)**

**Comment by mlorbetske** [comment]
@dotnet-bot test this please

File: src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/RunnableProjectGenerator.cs [hunk 1]
```diff
@@ -256,6 +256,77 @@ public bool TryGetTemplateFromConfigInfo(IFileSystemInfo templateFileConfig, out
...
+                }
+
+                if (string.IsNullOrEmpty(templateModel.Name))
+                {
+                    errorMessages.Add(string.Format(LocalizableStrings.Authoring_MissingValue, "name", templateFile.FullPath));
+                }
+
+                if ((templateModel.ShortNameList?.Count ?? 0) == 0)
+                {
+                    errorMessages.Add(string.Format(LocalizableStrings.Authoring_MissingValue, "shortName", templateFile.FullPath));
```
Comment (seancpeters) [inline src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/RunnableProjectGenerator.cs]: Should this be just a warning? I wasn't clear if we'd finalized whether short name should be required or not.
