### PR TITLE
Make setup better

### LINKED ISSUE #488: BadPackageSpec Errors on the very first use of `new3` on Mac OS X
I've installed local version of the tool on Mac OS Sierra and have no problem during install.
On the very first use of the cli tool I've got this errors:
```bash
dotnet new3 -all
Getting ready...
Error: Package "%DN3%\..\artifacts\packages" is not a valid package specification.
Error: Package "%DN3%\..\template_feed\" is not a valid package specification.
Template Instantiation Commands for .NET Core CLI
....
```
Something similar to cases here:
https://github.com/dotnet/templating/blob/0aab536d22afeeda918bc78190bf649f0e4fb685/src/Microsoft.TemplateEngine.Cli/Installer.cs#L138-L143

The list of templates for `new3` is empty:
```bash
dotnet new3 --list
Template Instantiation Commands for .NET Core CLI

Usage: dotnet new3 [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         Lists templates containing the specified name. If no name is specified, lists all templates.
  -lang|--language  Specifies the language of the template to create.
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  --type            Shows a subset of the available templates. Valid values are "project", "item" or "other".
  --force           Forces content to be generated even if it would change existing files.
  --allow-scripts   Specify if post action scripts should run.


Templates      Short Name      Language      Tags
-------------------------------------------------
```
The `dotnet new --list` returns on the other hand:
```
Templates          Short Name       Language      Tags    
----------------------------------------------------------
Nuget Config       nugetconfig                    Config  
Web Config         webconfig                      Config  
Solution File      sln                            Solution
```
Dotnet info:
https://github.com/dotnet/cli/releases/tag/v1.0.1
```bash
dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

### PR DESCRIPTION
**Pull request by mlorbetske**
Fixes #488

### CODE REVIEW

File: harderreset.sh [hunk 1]
```diff
@@ -14,7 +14,7 @@ for proj in `ls -1G $DN3BASEDIR/src`; do
 done
 
 echo "Removing ~/.netnew..."
```
Comment (seancpeters) [inline harderreset.sh]: Message should correspond to the action - removing "~/.templateengine"
